---

- name: Disable swap
  import_tasks: swapoff.yml

- name: Install docker
  import_tasks: docker.yml

- name: Add repo key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add kubernetes repo
  apt_repository: 
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main' 
    state: present 
    update_cache: yes

- name: Install kubernetes packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Kubeadm init
  command: kubeadm init --pod-network-cidr={{kubernete_cluster_cidr}}
  args:
    creates: /etc/kubernetes/pki

- sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Make admin.conf readable
  file:
    path: /etc/kubernetes/admin.conf
    mode: u=rwX,g=rX,o=rX

- copy:
    dest: /etc/profile.d/kube.sh
    content: "export KUBECONFIG=/etc/kubernetes/admin.conf"

  # master nodes by default have a taint applied that causes all 
  # pods, that lack node-role.kubernetes.io/master tolerations, 
  # to be scheduled on other nodes in the cluster
  # this command removes that taint and allows all pods to run on this
  # single node cluster 
- name: check for master taint
  shell: "kubectl --kubeconfig /etc/kubernetes/admin.conf describe nodes | grep 'Taints:             <none>' | wc -l"
  args:
    executable: /bin/bash
  register: taint_check

#- debug: msg={{taint_check}}

- name: Taint the master node
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: taint_check.stdout == "0"

- shell: "kubectl --kubeconfig /etc/kubernetes/admin.conf version | base64 | tr -d '\n'"
  args:
    executable: /bin/bash
  register: kubever

- debug: msg={{kubever}}

- name: Install Weave
  shell: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f "https://cloud.weave.works/k8s/net?k8s-version={{kubever.stdout}}"
  args:
    executable: /bin/bash
